"""initial schema

Revision ID: 58bb87d61e5d
Revises: 
Create Date: 2026-04-05 21:16:44.985928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bb87d61e5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sire', sa.String(), nullable=True),
    sa.Column('dam', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('trainer_name', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('greyhound_data_id', sa.String(), nullable=True),
    sa.Column('gri_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('greyhound_data_id'),
    sa.UniqueConstraint('gri_id')
    )
    op.create_index(op.f('ix_dogs_id'), 'dogs', ['id'], unique=False)
    op.create_index(op.f('ix_dogs_name'), 'dogs', ['name'], unique=False)
    op.create_index(op.f('ix_dogs_trainer_name'), 'dogs', ['trainer_name'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('feature_set', sa.JSON(), nullable=False),
    sa.Column('split_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('confusion_matrix', sa.JSON(), nullable=True),
    sa.Column('calibration_data', sa.JSON(), nullable=True),
    sa.Column('roc_data', sa.JSON(), nullable=True),
    sa.Column('shap_summary', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('training_duration_s', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_table('feature_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_type', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('input_columns', sa.JSON(), nullable=True),
    sa.Column('output_dtype', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_feature_definitions_id'), 'feature_definitions', ['id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('distances_m', sa.JSON(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('num_traps', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('race_time', sa.Time(), nullable=True),
    sa.Column('race_number', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('race_type', sa.String(), nullable=True),
    sa.Column('prize_money', sa.Float(), nullable=True),
    sa.Column('going', sa.String(), nullable=True),
    sa.Column('going_allowance', sa.Float(), nullable=True),
    sa.Column('num_runners', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'race_date', 'race_number', name='uq_race_track_date_num')
    )
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_index(op.f('ix_races_race_date'), 'races', ['race_date'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('odds_decimal', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('is_sp', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_id'), 'odds_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_race_id'), 'odds_snapshots', ['race_id'], unique=False)
    op.create_table('race_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('trap', sa.Integer(), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('finish_time', sa.Float(), nullable=True),
    sa.Column('sectional_time', sa.Float(), nullable=True),
    sa.Column('adjusted_time', sa.Float(), nullable=True),
    sa.Column('beaten_distance', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('starting_price', sa.String(), nullable=True),
    sa.Column('sp_decimal', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('wide_runner', sa.Boolean(), nullable=True),
    sa.Column('grade_at_entry', sa.String(), nullable=True),
    sa.Column('days_since_last', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'trap', name='uq_entry_race_trap')
    )
    op.create_index(op.f('ix_race_entries_dog_id'), 'race_entries', ['dog_id'], unique=False)
    op.create_index(op.f('ix_race_entries_id'), 'race_entries', ['id'], unique=False)
    op.create_index(op.f('ix_race_entries_race_id'), 'race_entries', ['race_id'], unique=False)
    op.create_table('computed_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_entry_id', sa.Integer(), nullable=False),
    sa.Column('feature_def_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feature_def_id'], ['feature_definitions.id'], ),
    sa.ForeignKeyConstraint(['race_entry_id'], ['race_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_entry_id', 'feature_def_id', name='uq_computed_entry_feature')
    )
    op.create_index(op.f('ix_computed_features_id'), 'computed_features', ['id'], unique=False)
    op.create_index(op.f('ix_computed_features_race_entry_id'), 'computed_features', ['race_entry_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('race_entry_id', sa.Integer(), nullable=False),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('predicted_position', sa.Float(), nullable=True),
    sa.Column('predicted_time', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['race_entry_id'], ['race_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'race_entry_id', name='uq_prediction_exp_entry')
    )
    op.create_index(op.f('ix_predictions_experiment_id'), 'predictions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_race_entry_id'), 'predictions', ['race_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_race_entry_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_experiment_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_computed_features_race_entry_id'), table_name='computed_features')
    op.drop_index(op.f('ix_computed_features_id'), table_name='computed_features')
    op.drop_table('computed_features')
    op.drop_index(op.f('ix_race_entries_race_id'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_id'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_dog_id'), table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_index(op.f('ix_odds_snapshots_race_id'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_races_race_date'), table_name='races')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_table('races')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_feature_definitions_id'), table_name='feature_definitions')
    op.drop_table('feature_definitions')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_dogs_trainer_name'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_name'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_id'), table_name='dogs')
    op.drop_table('dogs')
    # ### end Alembic commands ###
